### ISSUE TITLE
Daot vittuilee

### ISSUE THREAD

**Issue by quantti** [quantti/Noble-n-Agile-Magicians-ohtu-mini#10]
Jos joku tarkkasilmäinen keksii miten KäyttöliittymäInterfacen haeYksiKirja ja haeYksiVideo sekä niitä vastaavat Dao-kutsut eroavat toiminnallisuudeltaan, niin olisi kiva. Toisessa kun jostain syystä pitää castata tuo palautettu olio.

**Comment by virtalas** [comment]
Korjattu pull requestissä https://github.com/quantti/Noble-n-Agile-Magicians-ohtu-mini/pull/17

**Comment by quantti** [comment]
Hei, kiitos. Enpäs ollut tajunnut että ne siellä ylhäällä oli vielä tuossa mallissa.
