### ISSUE TITLE
Pienempi kuin merkki tulostuu väärään kohtaan

### ISSUE THREAD

**Issue by quantti** [quantti/Noble-n-Agile-Magicians-ohtu-mini#3]
Pienet on viat, mutta aivan saatanan raskas on. Eli tuossa "käyttöliittymässä" pienempi kuin -merkin pitäisi tulostua tietysti ennen kuin käyttäjältä kysytään vaihtoehtoa, mutta sepä nyt väkisin tulostuu sen jälkeen. Niinku miks?

**Comment by quantti** [comment]
Tai siis suurempi kuin... Vaikeita nää matematiikan symbolit.

**Comment by andeem** [comment]
Kokeilin nopeasti ja en saanut toistettua tätä omalla koneella. Ajoin ohjelmaa NetBeans:issä ja komentoriviltä sekä gradle run komennolla että jar:ina ja kaikki tulostui siinä järjestyksessä missä ne on koodissa.

**Comment by quantti** [comment]
Luulin jo tulevani hulluksi, mutta jotain bugia siis jossain tällä koneella. No sen kanssa voi ehkä elää.
